name: run script
  
on:  
  schedule:  
    - cron: '0 0 */3 * *'  # At midnight UTC, every 3 days
  push:
    branches:
      - main
  
jobs:  
  run:  
    runs-on: ubuntu-latest  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies  
      run: pip install -r requirements.pip 

    - name: Run Script
      run: python3 __init__.py

    - name: Compress logs
      if: always()
      run: |
        tar -cvf result.tar tests.txt components.txt

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: "result" 
        path: "result.tar"
